-- TABLE user_types CREATION
CREATE TABLE user_types (
  id_uty SERIAL PRIMARY KEY,
  name_uty VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- TABLE usuarios CREATION
CREATE TABLE usuarios (
  id_usr SERIAL PRIMARY KEY,
  user_name_usr VARCHAR(50) NOT NULL,
  email_usr VARCHAR(50) NOT NULL,
  password_usr VARCHAR(255) NOT NULL,
  fk_id_uty INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (fk_id_uty) REFERENCES user_types(id_uty)
);
-- TABLE profile CREATION
CREATE TABLE profile (
  id_prf SERIAL PRIMARY KEY,
  name_prf VARCHAR(50) NOT NULL,
  last_name_prf VARCHAR(50) NOT NULL,
  address_prf VARCHAR(500) NOT NULL,
  phone_prf VARCHAR(50) DEFAULT NULL,
  mobile_prf VARCHAR(50) DEFAULT NULL,
  photo_prf VARCHAR(500) DEFAULT NULL,
  fk_id_usr INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (fk_id_usr) REFERENCES usuarios(id_usr)
);
-- TABLE sector CREATION
CREATE TABLE sector (
  id_sec SERIAL PRIMARY KEY,
  name_sec VARCHAR(255) NOT NULL,
  paths_sec VARCHAR(666) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
-- TABLE alarm CREATION
CREATE TABLE alarm (
  id_alm SERIAL PRIMARY KEY,
  code_alm VARCHAR(50) NOT NULL,
  radio_alm INTEGER NOT NULL,
  ubicacion_alm VARCHAR(255),
  fk_id_usr INTEGER NOT NULL,
  fk_id_sec INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (fk_id_usr) REFERENCES usuarios(id_usr),
  FOREIGN KEY (fk_id_sec) REFERENCES sector(id_sec)
);